name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install tmux
      run: sudo apt-get update && sudo apt-get install -y tmux
    
    - name: Check Bash version
      run: bash --version
    
    - name: Run tests
      run: |
        bash test/test_ninja.sh